### ISSUE TITLE
There are missing features from requirement

### ISSUE THREAD

**Issue by hoangnguyen92dn** [PhanVanLinh/NBSurveyApp#53]
As you mentioned in the email with Ms. Uyen, seems you are busy with your personal stuff so you didn't have a chance to finish all the requirements. I'd like to list them here and please let me know if you are willing to update upon your spare time. And I see there are some pending issues tickets created so I'll note them here as well. 

- [ ] No delay and transition animation on Splash screen (#33)
- [ ] No shimmer loading animation (#36)
- [ ] No Today label on the Home screen
- [ ] No navigation indicator list (bullets) (#38)

Optional requirements:
- [ ] Implement the forgot password authentication screen.

**Comment by PhanVanLinh** [comment]
@hoangnguyen92dn Thank you for your feedback. You are right, I am missing those feature. For the remain feature, I have sorry to say that I can not done it. Because my current project feature will release next Monday so I have many tasks to do and also I have some meeting, code review, bug fixing with my team and also some interview with other company because I am looking for new job. Therefore, in my spare time in the end of day, I almost can not code. 

For the remain task, I would like to share some of my previous repository which quite same to the current requirement. I hope you can consider to review it as a reference
1) Feature home indicator: I do with many time in many projects but I don't keep the code. Basically, I create a custom view with multiple dots. The below repo have a same approach with indicator
https://github.com/PhanVanLinh/AndroidBottomMenu

2) Shimmer loading: I did it before when I working in a video social project (a project which like youtube), instead of using facebook library, I do the animation manually, I animate a vertical bar above a temporary ViewHolder (use RecyclerView with multiple type)
https://github.com/PhanVanLinh/AndroidVerticalLoading

3) SplashScreen and animation. I have not done the similar feature. 
https://github.com/PhanVanLinh/AndroidSplashScreen
https://github.com/PhanVanLinh?tab=repositories&q=animation&type=&language=&sort=

3) Today in home screen
I can do it using Calendar, we can not use JavaTime because we support from API>5

4) Forgot password authentication
This feature is quite same login feature, we will send a POST request to server

**Comment by sleepylee** [comment]
> I can do it using Calendar, we can not use JavaTime because we support from API>5

https://github.com/PhanVanLinh/NBSurveyApp/blob/main/app/build.gradle#L14 isn't it min required 21?

**Comment by PhanVanLinh** [comment]
sorry, my bad explain. I meaning we support from Android 5 but java.time was add from android 8 so we can not use it for current project (https://developer.android.com/reference/java/time/package-summary)

**Comment by sleepylee** [comment]
well if you notice, the Date is actually displaying above 😄  which is simply util.Date format (from SDK 1.1) https://developer.android.com/reference/java/util/Date
 😄  the Today is a label just simply to indicate the Date above is Today.

**Comment by PhanVanLinh** [comment]
yes, I forgot about this class :D, most of method in that `Date` class is deprecated so I don't use it often

**Comment by hoangnguyen92dn** [comment]
> For the remain task, I would like to share some of my previous repository which quite same to the current requirement. I hope you can consider to review it as a reference

Hi @PhanVanLinh 👋 

Just want to confirm with you. Regarding the issues created by us during the code review process, willing you to open new PRs to update the project in the next few days? I took a look at your repositories but there are quite updated for a long time (3-4 years ago) and from my point of view, I am going to evaluate your code challenge on this project only.

**Comment by PhanVanLinh** [comment]
@hoangnguyen92dn yes, I understand your point. Thank for your time for reviewing and feedback. I learn many things from your reviewing about code quality. Actually, I have did this project not very carefully, I skipped many common warnings from IDE. I feel not good because I think I should do better.  
I am sorry because I don't know the interview process can long like this. So I would like to drop this interview. I will improve my skill and I will apply later. In the next time, I will be more careful when coding.

**Comment by hoangnguyen92dn** [comment]
@PhanVanLinh Thanks so much for letting me know 👍  I appreciate your knowledge on the code challenge and I think you’re great. Wish you the best of luck in whatever you do next! 🍀  Have a nice day ☀️
